// Generated by CoffeeScript 1.10.0
(function() {
  var Utils, _, expect;

  expect = require('expect.js');

  _ = require('lodash');

  Utils = (function() {
    function Utils() {}

    Utils.prototype.padString = function(item) {
      var ref, value;
      value = ((ref = item.value) != null ? ref.toString().trim() : void 0) || '';
      return value.toString().trim() + new Array(item.length).fill(' ').join('').substring(value.length);
    };

    Utils.prototype.padNumber = function(item) {
      var ref, value;
      value = ((ref = item.value) != null ? ref.toString().trim() : void 0) || '';
      return new Array(item.length).fill('0').join('').substring(value.length) + value;
    };

    return Utils;

  })();

  module.exports = Utils;

}).call(this);
