// Generated by CoffeeScript 1.10.0
(function() {
  var Utils, _, expect;

  _ = require('lodash');

  expect = require('expect.js');

  Utils = require('../src/Utils');

  describe('Utils', function() {
    var utils;
    utils = null;
    beforeEach(function() {
      return utils = new Utils;
    });
    describe('padString', function() {
      it('should add whitespaces do the right of the value', function() {
        return expect(utils.padString({
          value: '123456',
          length: 10
        })).to.be('123456    ');
      });
      return it('should return whitespaces if value is undefined', function() {
        return expect(utils.padString({
          length: 10
        })).to.be('          ');
      });
    });
    return describe('padNumber', function() {
      it('should add zeroes do the left of the value', function() {
        return expect(utils.padNumber({
          value: '123456',
          length: 10
        })).to.be('0000123456');
      });
      return it('should return zeroes if value is undefined', function() {
        return expect(utils.padNumber({
          length: 10
        })).to.be('0000000000');
      });
    });
  });

}).call(this);
